apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-api
  template:
    metadata:
      labels:
        app: my-api
    spec:
      containers:
      - name: myapp
        image: antonlarichev/conv-api:1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
        env:
          - name: AMQP_EXCHANGE
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: AMQP_EXCHANGE
          - name: AMQP_USER
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: AMQP_USER
          - name: AMQP_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: AMQP_PASSWORD
          - name: AMQP_HOSTNAME
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: AMQP_HOSTNAME
        volumeMounts:
          - name: api-value
            mountPath: /opt/app/uploads
      volumes:
        - name: api-value
          persistentVolumeClaim:
            claimName: api-pvc



                

        
